inputs:
  admin: ~/Code/energy-infra/data/ne_50m_admin0.gpkg
  admin_code: ADM0_A3
  ntl_monthly: ~/Temp/data/ntl/monthly
  ntl_annual: ~/Temp/data/ntl_annual.tif
  pop: ~/Temp/data/ghs.tif
  urban: ~/Temp/data/urb.tif

outputs:
  base: ~/Temp/data/
  scratch: ~/data/scratch/
  targets: targets
  costs: costs
  guess: guess
  vector: guess_vec
  pop_elec: pop_elec
  local: lv

options:
  percentile: 70
  ntl_threshold: 0.1
  threads: 1
